/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as VolumeProfileRouteImport } from './routes/volume-profile'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as GlobalRouteImport } from './routes/global'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as BacktestingRouteImport } from './routes/backtesting'
import { Route as AlertRouteImport } from './routes/alert'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as ChartIndexRouteImport } from './routes/chart/index'
import { Route as NotesNewRouteImport } from './routes/notes/new'
import { Route as NoteIdRouteImport } from './routes/note.$id'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumeProfileRoute = VolumeProfileRouteImport.update({
  id: '/volume-profile',
  path: '/volume-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalRoute = GlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestingRoute = BacktestingRouteImport.update({
  id: '/backtesting',
  path: '/backtesting',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertRoute = AlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartIndexRoute = ChartIndexRouteImport.update({
  id: '/chart/',
  path: '/chart/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNewRoute = NotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIdRoute = NoteIdRouteImport.update({
  id: '/note/$id',
  path: '/note/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alert': typeof AlertRoute
  '/backtesting': typeof BacktestingRoute
  '/crypto': typeof CryptoRoute
  '/debug': typeof DebugRoute
  '/global': typeof GlobalRoute
  '/heatmap': typeof HeatmapRoute
  '/matrix': typeof MatrixRoute
  '/signals': typeof SignalsRoute
  '/skills': typeof SkillsRoute
  '/sync': typeof SyncRoute
  '/volume-profile': typeof VolumeProfileRoute
  '/watch': typeof WatchRoute
  '/note/$id': typeof NoteIdRoute
  '/notes/new': typeof NotesNewRoute
  '/chart': typeof ChartIndexRoute
  '/notes': typeof NotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alert': typeof AlertRoute
  '/backtesting': typeof BacktestingRoute
  '/crypto': typeof CryptoRoute
  '/debug': typeof DebugRoute
  '/global': typeof GlobalRoute
  '/heatmap': typeof HeatmapRoute
  '/matrix': typeof MatrixRoute
  '/signals': typeof SignalsRoute
  '/skills': typeof SkillsRoute
  '/sync': typeof SyncRoute
  '/volume-profile': typeof VolumeProfileRoute
  '/watch': typeof WatchRoute
  '/note/$id': typeof NoteIdRoute
  '/notes/new': typeof NotesNewRoute
  '/chart': typeof ChartIndexRoute
  '/notes': typeof NotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alert': typeof AlertRoute
  '/backtesting': typeof BacktestingRoute
  '/crypto': typeof CryptoRoute
  '/debug': typeof DebugRoute
  '/global': typeof GlobalRoute
  '/heatmap': typeof HeatmapRoute
  '/matrix': typeof MatrixRoute
  '/signals': typeof SignalsRoute
  '/skills': typeof SkillsRoute
  '/sync': typeof SyncRoute
  '/volume-profile': typeof VolumeProfileRoute
  '/watch': typeof WatchRoute
  '/note/$id': typeof NoteIdRoute
  '/notes/new': typeof NotesNewRoute
  '/chart/': typeof ChartIndexRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/alert'
    | '/backtesting'
    | '/crypto'
    | '/debug'
    | '/global'
    | '/heatmap'
    | '/matrix'
    | '/signals'
    | '/skills'
    | '/sync'
    | '/volume-profile'
    | '/watch'
    | '/note/$id'
    | '/notes/new'
    | '/chart'
    | '/notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/alert'
    | '/backtesting'
    | '/crypto'
    | '/debug'
    | '/global'
    | '/heatmap'
    | '/matrix'
    | '/signals'
    | '/skills'
    | '/sync'
    | '/volume-profile'
    | '/watch'
    | '/note/$id'
    | '/notes/new'
    | '/chart'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/alert'
    | '/backtesting'
    | '/crypto'
    | '/debug'
    | '/global'
    | '/heatmap'
    | '/matrix'
    | '/signals'
    | '/skills'
    | '/sync'
    | '/volume-profile'
    | '/watch'
    | '/note/$id'
    | '/notes/new'
    | '/chart/'
    | '/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AlertRoute: typeof AlertRoute
  BacktestingRoute: typeof BacktestingRoute
  CryptoRoute: typeof CryptoRoute
  DebugRoute: typeof DebugRoute
  GlobalRoute: typeof GlobalRoute
  HeatmapRoute: typeof HeatmapRoute
  MatrixRoute: typeof MatrixRoute
  SignalsRoute: typeof SignalsRoute
  SkillsRoute: typeof SkillsRoute
  SyncRoute: typeof SyncRoute
  VolumeProfileRoute: typeof VolumeProfileRoute
  WatchRoute: typeof WatchRoute
  NoteIdRoute: typeof NoteIdRoute
  NotesNewRoute: typeof NotesNewRoute
  ChartIndexRoute: typeof ChartIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume-profile': {
      id: '/volume-profile'
      path: '/volume-profile'
      fullPath: '/volume-profile'
      preLoaderRoute: typeof VolumeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global': {
      id: '/global'
      path: '/global'
      fullPath: '/global'
      preLoaderRoute: typeof GlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtesting': {
      id: '/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof BacktestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert': {
      id: '/alert'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart/': {
      id: '/chart/'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/new': {
      id: '/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof NotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$id': {
      id: '/note/$id'
      path: '/note/$id'
      fullPath: '/note/$id'
      preLoaderRoute: typeof NoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AlertRoute: AlertRoute,
  BacktestingRoute: BacktestingRoute,
  CryptoRoute: CryptoRoute,
  DebugRoute: DebugRoute,
  GlobalRoute: GlobalRoute,
  HeatmapRoute: HeatmapRoute,
  MatrixRoute: MatrixRoute,
  SignalsRoute: SignalsRoute,
  SkillsRoute: SkillsRoute,
  SyncRoute: SyncRoute,
  VolumeProfileRoute: VolumeProfileRoute,
  WatchRoute: WatchRoute,
  NoteIdRoute: NoteIdRoute,
  NotesNewRoute: NotesNewRoute,
  ChartIndexRoute: ChartIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
